"""Add new columns for Application

Revision ID: c13c82157229
Revises: 6760ab5cf01f
Create Date: 2026-08-08 20:49:26.649710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c13c82157229'
down_revision: Union[str, Sequence[str], None] = '6760ab5cf01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('job_link', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('offer_date', sa.Date(), nullable=True))
    op.add_column('applications', sa.Column('response_deadline', sa.Date(), nullable=True))
    op.add_column('applications', sa.Column('tags', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.alter_column('applications', 'applied_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('applications', 'salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_applications_company'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_column('applications', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_company'), 'applications', ['company'], unique=False)
    op.alter_column('applications', 'salary',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('applications', 'applied_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('applications', 'tags')
    op.drop_column('applications', 'response_deadline')
    op.drop_column('applications', 'offer_date')
    op.drop_column('applications', 'job_link')
    # ### end Alembic commands ###
