import type { Application } from './models'

export const mockApplications: Application[] = [
  {
    company: 'Fitzgerald PLC',
    role: 'DevOps Engineer',
    status: 'rejected',
    salary: null,
    notes: null,
    applied_date: '2026-05-29T13:34:26.509416',
    id: 1,
  },
  {
    company: 'Cunningham Ltd',
    role: 'DevOps Engineer',
    status: 'applied',
    salary: null,
    notes: null,
    applied_date: '2026-04-08T13:34:26.509532',
    id: 2,
  },
  {
    company: 'Wang Ltd',
    role: 'Site Reliability Engineer',
    status: 'interview',
    salary: null,
    notes: null,
    applied_date: '2026-02-23T13:34:26.509609',
    id: 3,
  },
  {
    company: 'Evans, Rivera and Chapman',
    role: 'Backend Engineer',
    status: 'offer',
    salary: 126000,
    notes:
      'Blue cup religious policy save sell performance his field conference.',
    applied_date: '2026-03-09T13:34:26.509783',
    id: 4,
  },
  {
    company: 'Nielsen Inc',
    role: 'Frontend Engineer',
    status: 'interview',
    salary: null,
    notes: 'Itself write tough hand hear traditional identify appear.',
    applied_date: '2026-07-29T13:34:26.509869',
    id: 5,
  },
  {
    company: 'Barton and Sons',
    role: 'Frontend Engineer',
    status: 'rejected',
    salary: null,
    notes:
      'Media fish agreement mean entire capital top us agreement crime receive baby determine.',
    applied_date: '2026-07-06T13:34:26.509949',
    id: 6,
  },
  {
    company: 'Ingram-Austin',
    role: 'QA Engineer',
    status: 'applied',
    salary: null,
    notes:
      'Budget near many project task support author visit local guy least.',
    applied_date: '2026-07-04T13:34:26.510081',
    id: 7,
  },
  {
    company: 'Hudson, Cooper and Page',
    role: 'Machine Learning Engineer',
    status: 'interview',
    salary: null,
    notes:
      'Government way author environment but whose chance from agent list officer.',
    applied_date: '2026-05-27T13:34:26.510238',
    id: 8,
  },
  {
    company: 'Lopez, King and Palmer',
    role: 'Product Manager',
    status: 'applied',
    salary: null,
    notes: 'News wait site manager with full out.',
    applied_date: '2026-04-03T13:34:26.510392',
    id: 9,
  },
  {
    company: 'Peterson and Sons',
    role: 'Site Reliability Engineer',
    status: 'interview',
    salary: null,
    notes: 'Door a to cultural marriage natural through billion.',
    applied_date: '2026-07-16T13:34:26.510467',
    id: 10,
  },
  {
    company: 'Thomas Ltd',
    role: 'DevOps Engineer',
    status: 'interview',
    salary: null,
    notes: 'House least brother truth commercial reduce thought head.',
    applied_date: '2026-06-27T13:34:26.510540',
    id: 11,
  },
  {
    company: 'Gonzalez PLC',
    role: 'QA Engineer',
    status: 'applied',
    salary: null,
    notes: 'Thought energy decade economic carry use indicate wait.',
    applied_date: '2026-06-18T13:34:26.510613',
    id: 12,
  },
  {
    company: 'Dunn, Ortiz and Smith',
    role: 'Data Engineer',
    status: 'rejected',
    salary: null,
    notes: null,
    applied_date: '2026-03-15T13:34:26.510754',
    id: 13,
  },
  {
    company: 'Hall, Baker and Faulkner',
    role: 'QA Engineer',
    status: 'applied',
    salary: null,
    notes: null,
    applied_date: '2026-07-09T13:34:26.510896',
    id: 14,
  },
  {
    company: 'Kim, Hernandez and Baker',
    role: 'QA Engineer',
    status: 'applied',
    salary: null,
    notes: 'Meet beyond economy help over join court.',
    applied_date: '2026-04-12T13:34:26.511056',
    id: 15,
  },
  {
    company: 'Wright, Jenkins and Robinson',
    role: 'Full Stack Engineer',
    status: 'interview',
    salary: null,
    notes: 'Left both respond keep thank they word go something.',
    applied_date: '2026-03-22T13:34:26.511207',
    id: 16,
  },
  {
    company: 'Strong-Taylor',
    role: 'Engineering Manager',
    status: 'applied',
    salary: null,
    notes: 'Indeed hope consider old or be big create worker term increase.',
    applied_date: '2026-06-10T13:34:26.511321',
    id: 17,
  },
  {
    company: 'Flores, Watkins and Stewart',
    role: 'Data Engineer',
    status: 'rejected',
    salary: null,
    notes: null,
    applied_date: '2026-03-28T13:34:26.511462',
    id: 18,
  },
  {
    company: 'Garcia Ltd',
    role: 'Engineering Manager',
    status: 'interview',
    salary: null,
    notes: 'Manage leader imagine carry tree thousand hope early tree.',
    applied_date: '2026-05-24T13:34:26.511534',
    id: 19,
  },
  {
    company: 'Smith, Williams and Lawson',
    role: 'Frontend Engineer',
    status: 'rejected',
    salary: null,
    notes: 'Science out goal artist citizen military better.',
    applied_date: '2026-08-02T13:34:26.511684',
    id: 20,
  },
  {
    company: 'Benson-Davidson',
    role: 'Data Engineer',
    status: 'applied',
    salary: null,
    notes:
      'Day worry brother section first garden down hundred participant do reveal high.',
    applied_date: '2026-05-22T13:34:26.511793',
    id: 21,
  },
  {
    company: 'Jennings Ltd',
    role: 'Full Stack Engineer',
    status: 'applied',
    salary: null,
    notes: null,
    applied_date: '2026-06-21T13:34:26.511862',
    id: 22,
  },
  {
    company: 'Ruiz, Hardin and Carey',
    role: 'DevOps Engineer',
    status: 'rejected',
    salary: null,
    notes: null,
    applied_date: '2026-02-16T13:34:26.512015',
    id: 23,
  },
  {
    company: 'Martin Ltd',
    role: 'DevOps Engineer',
    status: 'interview',
    salary: null,
    notes: 'Successful door material fund government clear news program but.',
    applied_date: '2026-07-28T13:34:26.512089',
    id: 24,
  },
  {
    company: 'Mills PLC',
    role: 'QA Engineer',
    status: 'interview',
    salary: null,
    notes:
      'Agreement fire seem minute church court though bit traditional institution while major.',
    applied_date: '2026-07-27T13:34:26.512162',
    id: 25,
  },
]
